<?php

namespace AppBundle\Repository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends \Doctrine\ORM\EntityRepository
{
	public function count()
    {
        return $this
            ->createQueryBuilder('object')
            ->select("count(object.id)")
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findByPage($page){
    	$pageSize = 6;
        $query = $this->createQueryBuilder('cl')
                      ->orderBy('cl.id', 'DESC')
                      ->getQuery()
                      ->setFirstResult($pageSize * ($page-1))
    				  ->setMaxResults($pageSize)
                      ->getResult()
                      ;
        return $query;

    }
}
